// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avqlisqqhwqvdagkmewu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2cWxpc3FxaHdxdmRhZ2ttZXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjI1ODQsImV4cCI6MjA3MzA5ODU4NH0.zXJ0miHiSQPdd0MJvd_--YNFMrAxr2LlGRXixrcX8L4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
